version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7057:7057"
    environment:
      - ASPNETCORE_URLS=http://+:7057
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Server=db;Database=TechChallenge;User=sa;Password=2025@_Futuro;Encrypt=False;TrustServerCertificate=True;
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: techchallenge_sqlserver
    environment:
      SA_PASSWORD: "2025@_Futuro"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"