// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace UnitTests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class CriarPedidoFeature : object, global::Xunit.IClassFixture<CriarPedidoFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("pt"), "Features", "Criar Pedido", "    Como um sistema de autoatendimento\r\n    Gostaria de criar pedidos com produto" +
                "s e ingredientes extras\r\n    Para que a cozinha possa preparar", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "CreateOrder.feature"
#line hidden
        
        public CriarPedidoFeature(CriarPedidoFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/CreateOrder.feature.ndjson", 7);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Criar pedido com cliente identificado e itens validos")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Criar Pedido")]
        [global::Xunit.TraitAttribute("Description", "Criar pedido com cliente identificado e itens validos")]
        public async global::System.Threading.Tasks.Task CriarPedidoComClienteIdentificadoEItensValidos()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Criar pedido com cliente identificado e itens validos", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 7
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
        await testRunner.GivenAsync("que existe um cliente na base com ID \"cli-01\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 9
        await testRunner.AndAsync("que existe um produto com ID \"prod-01\" Nome \"X-Burger\" e Preco 20.00", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 10
        await testRunner.AndAsync("que existe um ingrediente com ID \"ing-01\" Nome \"Bacon Extra\" e Preco 3.00", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 11
        await testRunner.WhenAsync("eu monto um pedido para o cliente \"cli-01\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 12
        await testRunner.AndAsync("adiciono 1 unidade do produto \"prod-01\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 13
        await testRunner.AndAsync("adiciono o ingrediente \"ing-01\" no produto \"prod-01\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 14
        await testRunner.ThenAsync("o pedido deve ser salvo com sucesso", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entao ");
#line hidden
#line 15
        await testRunner.AndAsync("o gateway de pedidos deve ter sido chamado", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Criar pedido anonimo com sucesso")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Criar Pedido")]
        [global::Xunit.TraitAttribute("Description", "Criar pedido anonimo com sucesso")]
        public async global::System.Threading.Tasks.Task CriarPedidoAnonimoComSucesso()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Criar pedido anonimo com sucesso", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 17
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 18
        await testRunner.GivenAsync("que existe um produto com ID \"prod-02\" Nome \"Coca-Cola\" e Preco 5.00", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 19
        await testRunner.WhenAsync("eu monto um pedido sem cliente identificado", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 20
        await testRunner.AndAsync("adiciono 2 unidades do produto \"prod-02\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 21
        await testRunner.ThenAsync("o pedido deve ser salvo com sucesso", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entao ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Falhar ao tentar criar pedido para cliente inexistente")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Criar Pedido")]
        [global::Xunit.TraitAttribute("Description", "Falhar ao tentar criar pedido para cliente inexistente")]
        public async global::System.Threading.Tasks.Task FalharAoTentarCriarPedidoParaClienteInexistente()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Falhar ao tentar criar pedido para cliente inexistente", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 23
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 24
        await testRunner.GivenAsync("que o cliente com ID \"cli-99\" nao existe", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 25
        await testRunner.AndAsync("que existe um produto com ID \"prod-01\" Nome \"X-Burger\" e Preco 20.00", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 26
        await testRunner.WhenAsync("eu monto um pedido para o cliente \"cli-99\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 27
        await testRunner.AndAsync("adiciono 1 unidade do produto \"prod-01\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 28
        await testRunner.ThenAsync("o sistema deve retornar um erro contendo \"Cliente com ID\" e \"não encontrado\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entao ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Falhar ao tentar pedir produto inexistente")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Criar Pedido")]
        [global::Xunit.TraitAttribute("Description", "Falhar ao tentar pedir produto inexistente")]
        public async global::System.Threading.Tasks.Task FalharAoTentarPedirProdutoInexistente()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Falhar ao tentar pedir produto inexistente", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 30
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 31
        await testRunner.GivenAsync("que existe um cliente na base com ID \"cli-01\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 32
        await testRunner.ButAsync("o produto com ID \"prod-99\" nao existe na base", ((string)(null)), ((global::Reqnroll.Table)(null)), "Mas ");
#line hidden
#line 33
        await testRunner.WhenAsync("eu monto um pedido para o cliente \"cli-01\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 34
        await testRunner.AndAsync("adiciono 1 unidade do produto \"prod-99\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 35
        await testRunner.ThenAsync("o sistema deve retornar um erro contendo \"Os seguintes produtos não foram encontr" +
                        "ados\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entao ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Falhar ao tentar pedir ingrediente inexistente")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Criar Pedido")]
        [global::Xunit.TraitAttribute("Description", "Falhar ao tentar pedir ingrediente inexistente")]
        public async global::System.Threading.Tasks.Task FalharAoTentarPedirIngredienteInexistente()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Falhar ao tentar pedir ingrediente inexistente", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 37
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 38
        await testRunner.GivenAsync("que existe um produto com ID \"prod-01\" Nome \"Lanche\" e Preco 10.00", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 39
        await testRunner.ButAsync("o ingrediente com ID \"ing-99\" nao existe na base", ((string)(null)), ((global::Reqnroll.Table)(null)), "Mas ");
#line hidden
#line 40
        await testRunner.WhenAsync("eu monto um pedido sem cliente identificado", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 41
        await testRunner.AndAsync("adiciono 1 unidade do produto \"prod-01\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 42
        await testRunner.AndAsync("adiciono o ingrediente \"ing-99\" no produto \"prod-01\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 43
        await testRunner.ThenAsync("o sistema deve retornar um erro contendo \"Os seguintes ingredientes não foram enc" +
                        "ontrados\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entao ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await CriarPedidoFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await CriarPedidoFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
