version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7057:7057"
    volumes:
      - ./tech-challenge-imagens:/app/wwwroot
    environment:
      - ASPNETCORE_URLS=http://+:7057
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Server=db;Database=TechChallenge;User=sa;Password=TechChalleng@_Fase1;Encrypt=False;TrustServerCertificate=True;
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: techchallenge_sqlserver
    environment:
      SA_PASSWORD: "TechChalleng@_Fase1"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"